# Generated by Django 5.1.4 on 2025-02-03 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Pet_MNG', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kennel',
            fields=[
                ('kennel_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('is_occupied', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='KennelAssignment',
            fields=[
                ('assignment_id', models.AutoField(primary_key=True, serialize=False)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('kennel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Kennel_MNG.kennel')),
                ('pet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Pet_MNG.pet')),
            ],
        ),
    ]
