# Generated by Django 5.1.4 on 2025-01-22 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Employee_MNG', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='manager', to='Employee_MNG.employee')),
            ],
        ),
    ]
