# Generated by Django 5.1.4 on 2025-01-31 03:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Pet_MNG', '0001_initial'),
        ('Veterinarian_MNG', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExaminationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('diagnosis', models.TextField()),
                ('treatment', models.TextField()),
                ('stay_required', models.BooleanField(default=False)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pet_MNG.pet')),
                ('veterinarian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Veterinarian_MNG.veterinarian')),
            ],
        ),
    ]
