# Generated by Django 5.1.4 on 2025-01-02 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Veterinarian',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('specialization', models.CharField(max_length=255)),
            ],
        ),
    ]
