# Generated by Django 5.1.4 on 2025-01-02 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TreatmentRecord',
            fields=[
                ('record_id', models.AutoField(primary_key=True, serialize=False)),
                ('pet_id', models.IntegerField()),
                ('veterinarian_id', models.IntegerField()),
                ('diagnosis', models.TextField()),
                ('prescriptions', models.TextField()),
                ('notes', models.TextField()),
            ],
        ),
    ]
