# Generated by Django 5.1.4 on 2025-02-05 02:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Kennel_MNG', '0001_initial'),
        ('Pet_MNG', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalizationRecord',
            fields=[
                ('record_id', models.AutoField(primary_key=True, serialize=False)),
                ('admitted_at', models.DateTimeField(auto_now_add=True)),
                ('discharged_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('kennel_assignment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Kennel_MNG.kennelassignment')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pet_MNG.pet')),
            ],
        ),
    ]
