version: '3.4'

services:
  chude21:
    image: chude21
    build:
      context: .
      dockerfile: ./Dockerfile
    command: "python -m debugpy --wait-for-client --listen 0.0.0.0:5678 wed21/QL_Care_Health/manage.py runserver 0.0.0.0:8000 --nothreading --noreload"
    ports:
      - 8000:8000
      - 5678:5678
